module.exports = error => { return (req, res, next) => { error(req, res, next).catch((error) => next(error)) } }